name: Build Checklist
on: [push]

jobs:
  build_tools:
    runs-on: ubuntu-latest
    steps:
    - name: Check out checklist code
      uses: actions/checkout@v2
    - name: List Working Directory
      run: |
        pwd
        ls -la
    - name: Compile Checklist
      run: make
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: checklist
        path: |
          output.json
          output.xml
    - name: Publish Release
      uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/main'
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: output.xml

